javax:
  sql:
    DataSource:
      greetingDataSource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        dataSource:
          url: jdbc:postgresql://localhost:5432/testdb
          user: postgres
          password: postgresPwd